### ISSUE TITLE
TLS 1.2 Support

### ISSUE THREAD

**Issue by dmarjoram** [auth0-samples/auth0-aspnet-owin-mvc-samples#17]
See ticket here:
https://support.auth0.com/tickets/48726

See pull request here:
https://github.com/auth0-samples/auth0-aspnet-owin-mvc-samples/pull/16

Hi there,

We've got a development team using the .NET OWIN quick start sample code from the auth0 samples github repository. out of the box, they were having a problem with the sample code due what looks like a TLS 1.2 secured endpoint that didn't allow downgrade. This was showing as the yellow screen of death.

Problem resolved with:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Would it be possible to update the sample code in the auth0 repo?

Kind Regards,
Darrell

**Comment by nicosabena** [comment]
Hi Darrell. Thanks for this report and the PR. I've mixed feelings about us putting a specific `ServicePointManager.SecurityProtocol` in the samples, as I believe it is too opinionated. Some examples:

 - in version 4.7 of the framework the recommended value is `SecurityProtocolType.SystemDefault` which will give you the best option available in the operating system where the app is running. 
- forcing TLS 1.2 might break development on older servers if they are not properly configured. 
- the setting affects the whole application, not just the OpenIDConnect middleware.

The subject is fairly complex (see https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls for details). [For people targetting the 4.5.2 version of the framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#for-net-framework-35---452-and-not-wcf) Microsoft recommends upgrading to 4.7. Read on for a couple of recommendations if that's not possible, but manually setting a `
ServicePointManager.SecurityProtocol` does not seem to be the recommended path.

It seems that, from a best practices point of view, we should upgrade our samples to 4.7 instead (which is always a tricky decision because compatibility with older systems might be affected).

**Comment by dmarjoram** [comment]
Agreed letting the operating system decide, or using system default would be the best option. The PR was intended as a quick fix as we are dealing with multiple teams that are using your samples and this has become a support issue for us. A lot of the systems we write and integrate with mandate TLS 1.2 support. As such, I suspect this will be reported by others if the samples are left targeting aging netfx.
